### ISSUE TITLE
Notificaciones

### ISSUE THREAD

**Issue by FranciscoJesusGata** [FranciscoJesusGata/proyecto4DSocialNetwork#35]
1. Front de Notificaciones.
2. Recepción de notificaciones (PHP).
3. Mostrar notificaciones (JQuery).
4. Mostrar notificaciones en detalle (Front de notificación en detalle)

**Comment by diegomonter** [comment]
El botón de notificaciones del navbar ya etá operativo, falta la página principal

**Comment by diegomonter** [comment]
Notificaciones ya está operativo, solo falta el refresco automático, esperaré hasta que tengamos los mensajes para replicarlo

**Comment by FranciscoJesusGata** [comment]
Página de notificaciones operativa
