### ISSUE TITLE
La clase Database no está adaptada para querys de varias tuplas

### ISSUE THREAD

**Issue by FranciscoJesusGata** [FranciscoJesusGata/proyecto4DSocialNetwork#53]
Hay que crear un método que haga un fetch array varias veces y guardar el resultado en una matriz (array multidimentsional).
|  1    2    3  |     1º Tupla
|  1    2    3  |     2º Tupla
|  1    2    3  |     3º Tupla

**Comment by diegomonter** [comment]
ya se ha adaptado, se usa de la misma manera que antes, pero ahora acepta varias tuplas
